// Animations for scrollVentana
export const scrollAnimList = [
  ["#about > div.titulo > h3", "abajo 500ms ease-in forwards"],
  ["#about > div.titulo > p", "abajo 800ms forwards"],
  ["#about > div.about-container > div.container-left", "aparecer 400ms ease-in 500ms forwards"],
  ["#about > div.about-container > div.container-right > div.right-texto", "arriba 500ms ease-in forwards"],
  ["#about > div.about-container > div.container-right > a", "arriba 500ms ease-in 500ms forwards"],
  ["#about > div.about-container > div.container-right > div.iconos > div:nth-child(1)", "abajo 500ms ease-in 200ms forwards"],
  ["#about > div.about-container > div.container-right > div.iconos > div:nth-child(2)", "abajo 500ms ease-in forwards"],
  ["#about > div.about-container > div.container-right > div.iconos > div:nth-child(3)", "abajo 500ms ease-in 200ms forwards"],
  ["#skills > span > div.container-texto", "abajo 500ms ease-in forwards"],
  ["#skills > span", "aparecer 500ms ease forwards"],
  ["#skills > span > div.sol", "aparecer 500ms ease 500ms forwards"],
  ["#skills > span > div:nth-child(3)", "aparecer 500ms ease 800ms forwards"],
  ["#portfolio > h1", "abajo 500ms ease forwards"],
  ["#portfolio > div > div:nth-child(1)", "aparecer 500ms ease 200ms forwards"],
  ["#portfolio > div > div:nth-child(2)", "aparecer 500ms ease 400ms forwards"],
  ["#portfolio > div > div:nth-child(3)", "aparecer 500ms ease 600ms forwards"],
  ["#portfolio > div > div:nth-child(4)", "aparecer 500ms ease 800ms forwards"],
  ["#portfolio > div > div:nth-child(5)", "aparecer 500ms ease 1000ms forwards"],
  ["#portfolio > div > div:nth-child(6)", "aparecer 500ms ease 1000ms forwards"],
  ["#contact h1", "abajo 500ms ease forwards"],
  ["#contact h6", "abajo 500ms ease 300ms forwards"],
  ["#contact > div > div.contact-left > p", "aparecer 500ms ease forwards"],
  ["#contact > div > div.contact-left > div.email", "toRight 1200ms ease forwards"],
  ["#contact > div > div.contact-left > div.whatsapp", "toRight 1200ms ease 500ms forwards"],
  ["#contact > div > div.contact-right > p", "aparecer 500ms ease forwards"],
  ["#contact > div > div.contact-right > div.mail-input", "toIzq 1200ms ease forwards "],
  ["#contact > div > div.contact-right > div.textarea-input", "toIzq 1200ms ease 500ms forwards"],
  ["#contact > div > div.contact-right > div.botonEnviar", "arriba 500ms ease 1300ms forwards"],
  [".footer > p.footer-name", "aparecer 500ms ease forwards"],
  [".footer > div > div:nth-child(1)", "arriba 500ms ease 300ms forwards"],
  [".footer > div > div:nth-child(2)", "arriba 500ms ease 600ms forwards"],
  [".footer > div > div:nth-child(3)", "arriba 500ms ease 800ms forwards"],
];
